<?php

use CRM_NcConfig_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_Fund_related',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Fund_related',
        'title' => E::ts('Fund-related'),
        'extends' => 'Organization',
        'extends_entity_column_value' => ['Investor'],
        'collapse_display' => TRUE,
        'collapse_adv_display' => TRUE,
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'CustomGroup_Fund_related_CustomField_Funds_Vintage_Year',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Fund_related',
        'name' => 'Funds_Vintage_Year',
        'label' => E::ts('Funds Vintage Year'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'text_length' => 255,
        'date_format' => 'yy',
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Focus',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Investment_Focus',
        'title' => E::ts('Investment-Focus'),
        'extends' => 'Individual',
        'extends_entity_column_value' => [
          'Investor_Representative',
        ],
        'collapse_display' => TRUE,
        'weight' => 2,
        'collapse_adv_display' => TRUE,
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_preferred_stages',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'eic_preferred_stages',
        'title' => E::ts('Preferred Stages'),
        'description' => E::ts('Preferred Stages'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_preferred_stages_OptionValue_Pre_Seed',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_preferred_stages',
        'label' => E::ts('Pre-Seed'),
        'value' => 'pre_seed',
        'name' => 'Pre-Seed',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_preferred_stages_OptionValue_Seed',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_preferred_stages',
        'label' => E::ts('Seed'),
        'value' => 'seed',
        'name' => 'Seed',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_preferred_stages_OptionValue_Series_A',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_preferred_stages',
        'label' => E::ts('Series A'),
        'value' => 'series_a',
        'name' => 'Series A',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_preferred_stages_OptionValue_Series_B',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_preferred_stages',
        'label' => E::ts('Series B'),
        'value' => 'series_b',
        'name' => 'Series B',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_preferred_stages_OptionValue_Growth_Late_stage',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_preferred_stages',
        'label' => E::ts('Growth/Late stage'),
        'value' => 'growth_late_stage',
        'name' => 'Growth/Late stage',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Focus_CustomField_Preferred_Stages',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Investment_Focus',
        'name' => 'Preferred_Stages',
        'label' => E::ts('Preferred Stages'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'option_group_id.name' => 'eic_preferred_stages',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_relevant_verticals',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'eic_relevant_verticals',
        'title' => E::ts('Relevant Verticals'),
        'description' => E::ts('Relevant Verticals'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_relevant_verticals_OptionValue_AI_Software',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_relevant_verticals',
        'label' => E::ts('AI & Software'),
        'value' => 'ai_and_software',
        'name' => 'AI & Software',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_relevant_verticals_OptionValue_Biotech',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_relevant_verticals',
        'label' => E::ts('Biotech'),
        'value' => 'biotech',
        'name' => 'Biotech',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_relevant_verticals_OptionValue_Consumer_Products_and_Services',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_relevant_verticals',
        'label' => E::ts('Consumer Products and Services'),
        'value' => 'consumer_products_and_services',
        'name' => 'Consumer Products and Services',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_relevant_verticals_OptionValue_Energy_Transition',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_relevant_verticals',
        'label' => E::ts('Energy Transition'),
        'value' => 'energy_transition',
        'name' => 'Energy Transition',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_relevant_verticals_OptionValue_Food_Agritech',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_relevant_verticals',
        'label' => E::ts('Food & Agritech'),
        'value' => 'food_and_agritech',
        'name' => 'Food & Agritech',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_relevant_verticals_OptionValue_MedTech',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_relevant_verticals',
        'label' => E::ts('MedTech'),
        'value' => 'medtech',
        'name' => 'MedTech',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_relevant_verticals_OptionValue_New_Materials_Industrial',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_relevant_verticals',
        'label' => E::ts('New Materials & Industrial'),
        'value' => 'new_materials_and_industrial',
        'name' => 'New Materials & Industrial',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_relevant_verticals_OptionValue_Semicon_Quantum',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_relevant_verticals',
        'label' => E::ts('Semicon & Quantum'),
        'value' => 'semicon_and_quantum',
        'name' => 'Semicon & Quantum',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_relevant_verticals_OptionValue_Space',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_relevant_verticals',
        'label' => E::ts('Space'),
        'value' => 'space',
        'name' => 'Space',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_relevant_verticals_OptionValue_Transport_Mobility',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_relevant_verticals',
        'label' => E::ts('Transport & Mobility'),
        'value' => 'transport_and_mobility',
        'name' => 'Transport & Mobility',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_relevant_verticals_OptionValue_Dual_use_Defense',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_relevant_verticals',
        'label' => E::ts('Dual use & Defense'),
        'value' => 'dual_use_and_defense',
        'name' => 'Dual use & Defense',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Focus_CustomField_Relevant_Verticals',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Investment_Focus',
        'name' => 'Relevant_Verticals',
        'label' => E::ts('Relevant Verticals'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'option_group_id.name' => 'eic_relevant_verticals',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_investor_role',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'eic_investor_role',
        'title' => E::ts('Role'),
        'description' => E::ts('Role'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_investor_role_OptionValue_Associate_Analyst',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_investor_role',
        'label' => E::ts('Associate/Analyst'),
        'value' => 'associate_analyst',
        'name' => 'Associate_Analyst',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_investor_role_OptionValue_General_Partner_Founder',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_investor_role',
        'label' => E::ts('General Partner/ Founder'),
        'value' => 'general_partner_founder',
        'name' => 'General_Partner_Founder',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_investor_role_OptionValue_Investment_Manager_Manager',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_investor_role',
        'label' => E::ts('Investment Manager/Manager'),
        'value' => 'investment_manager_manager',
        'name' => 'Investment_Manager_Manager',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_investor_role_OptionValue_Not_classifiable',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_investor_role',
        'label' => E::ts('Not classifiable'),
        'value' => 'not_classifiable',
        'name' => 'Not_classifiable',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_investor_role_OptionValue_Partner_Managing_Partner',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_investor_role',
        'label' => E::ts('Partner/Managing Partner'),
        'value' => 'partner_managing_partner',
        'name' => 'Partner_Managing_Partner',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_investor_role_OptionValue_Principal_Director',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_investor_role',
        'label' => E::ts('Principal/Director'),
        'value' => 'principal_director',
        'name' => 'Principal_Director',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_investor_role_OptionValue_Other',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_investor_role',
        'label' => E::ts('Other'),
        'value' => 'other',
        'name' => 'Other',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Focus_CustomField_Role',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Investment_Focus',
        'name' => 'Role',
        'label' => E::ts('Role'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'option_group_id.name' => 'eic_investor_role',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'eic_geographical_focus',
        'title' => E::ts('Geographical Focus'),
        'description' => E::ts('Geographical Focus'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Europe',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Europe'),
        'value' => 'EU',
        'name' => 'Europe',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Northern_Europe',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Northern Europe'),
        'value' => 'E1',
        'name' => 'Northern Europe',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Eastern_Europe',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Eastern Europe'),
        'value' => 'E2',
        'name' => 'Eastern Europe',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Southern_Europe',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Southern Europe'),
        'value' => 'E3',
        'name' => 'Southern Europe',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Western_Europe',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Western Europe'),
        'value' => 'E4',
        'name' => 'Western Europe',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Other_Countries',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Other Countries'),
        'value' => 'O1',
        'name' => 'Other Countries',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Other_European_Countries',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Other European Countries'),
        'value' => 'O2',
        'name' => 'Other European Countries',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Albania',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Albania'),
        'value' => 'AL',
        'name' => 'Albania',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Armenia',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Armenia'),
        'value' => 'AM',
        'name' => 'Armenia',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Austria',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Austria'),
        'value' => 'AT',
        'name' => 'Austria',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Belgium',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Belgium'),
        'value' => 'BE',
        'name' => 'Belgium',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Bosnia_and_Herzegovina',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Bosnia and Herzegovina'),
        'value' => 'BA',
        'name' => 'Bosnia and Herzegovina',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Bulgaria',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Bulgaria'),
        'value' => 'BG',
        'name' => 'Bulgaria',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Croatia',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Croatia'),
        'value' => 'HR',
        'name' => 'Croatia',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Cyprus',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Cyprus'),
        'value' => 'CY',
        'name' => 'Cyprus',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Czech_Republic',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Czech Republic'),
        'value' => 'CZ',
        'name' => 'Czech Republic',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Denmark',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Denmark'),
        'value' => 'DK',
        'name' => 'Denmark',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Estonia',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Estonia'),
        'value' => 'EE',
        'name' => 'Estonia',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Finland',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Finland'),
        'value' => 'FI',
        'name' => 'Finland',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_France',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('France'),
        'value' => 'FR',
        'name' => 'France',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Georgia',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Georgia'),
        'value' => 'GE',
        'name' => 'Georgia',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Germany',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Germany'),
        'value' => 'DE',
        'name' => 'Germany',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Greece',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Greece'),
        'value' => 'GR',
        'name' => 'Greece',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Hungary',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Hungary'),
        'value' => 'HU',
        'name' => 'Hungary',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Iceland',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Iceland'),
        'value' => 'IS',
        'name' => 'Iceland',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Ireland',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Ireland'),
        'value' => 'IE',
        'name' => 'Ireland',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Israel',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Israel'),
        'value' => 'IL',
        'name' => 'Israel',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Italy',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Italy'),
        'value' => 'IT',
        'name' => 'Italy',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Kosovo',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Kosovo'),
        'value' => 'XK',
        'name' => 'Kosovo',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Latvia',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Latvia'),
        'value' => 'LV',
        'name' => 'Latvia',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Lithuania',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Lithuania'),
        'value' => 'LT',
        'name' => 'Lithuania',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Luxembourg',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Luxembourg'),
        'value' => 'LU',
        'name' => 'Luxembourg',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Malta',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Malta'),
        'value' => 'MT',
        'name' => 'Malta',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Netherlands',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Netherlands'),
        'value' => 'NL',
        'name' => 'Netherlands',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_North_Macedonia',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('North Macedonia'),
        'value' => 'MK',
        'name' => 'North Macedonia',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Norway',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Norway'),
        'value' => 'NO',
        'name' => 'Norway',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Poland',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Poland'),
        'value' => 'PL',
        'name' => 'Poland',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Portugal',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Portugal'),
        'value' => 'PT',
        'name' => 'Portugal',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Romania',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Romania'),
        'value' => 'RO',
        'name' => 'Romania',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Serbia',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Serbia'),
        'value' => 'RS',
        'name' => 'Serbia',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Slovakia',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Slovakia'),
        'value' => 'SK',
        'name' => 'Slovakia',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Slovenia',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Slovenia'),
        'value' => 'SI',
        'name' => 'Slovenia',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Spain',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Spain'),
        'value' => 'ES',
        'name' => 'Spain',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Sweden',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Sweden'),
        'value' => 'SE',
        'name' => 'Sweden',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Switzerland',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Switzerland'),
        'value' => 'CH',
        'name' => 'Switzerland',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_T_rkiye',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Türkiye'),
        'value' => 'TR',
        'name' => 'Türkiye',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_Ukraine',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('Ukraine'),
        'value' => 'UA',
        'name' => 'Ukraine',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_geographical_focus_OptionValue_United_Kingdom',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_geographical_focus',
        'label' => E::ts('United Kingdom'),
        'value' => 'GB',
        'name' => 'United Kingdom',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Focus_CustomField_Geographical_Focus',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Investment_Focus',
        'name' => 'Geographical_Focus',
        'label' => E::ts('Geographical Focus'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'option_group_id.name' => 'eic_geographical_focus',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Focus_CustomField_Would_you_also_be_interested_in_working_with_firms_in_countries_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Investment_Focus',
        'name' => 'Would_you_also_be_interested_in_working_with_firms_in_countries_',
        'label' => E::ts('Would you also be interested in working with firms in countries associated to Horizon Europe'),
        'data_type' => 'Boolean',
        'html_type' => 'Toggle',
        'default_value' => '0',
        'help_post' => E::ts('Countries: Albania, Armenia, Bosnia and Herzegovina, Canada, Egypt, Faroe Islands, Georgia, Iceland, Israel, Korea, Kosovo, Moldova, Montenegro, New Zealand, North Macedonia, Norway, Serbia, Switzerland, Türkiye, Tunisia, Ukraine, United Kingdom'),
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Activity_related',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Activity_related',
        'title' => E::ts('Activity-related'),
        'extends' => 'Organization',
        'extends_entity_column_value' => ['Investor'],
        'collapse_display' => TRUE,
        'weight' => 3,
        'collapse_adv_display' => TRUE,
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'CustomGroup_Activity_related_CustomField_Onboarded',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Activity_related',
        'name' => 'Onboarded',
        'label' => E::ts('Onboarded'),
        'data_type' => 'Boolean',
        'html_type' => 'Toggle',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Activity_related_CustomField_Trusted_Investor_Network_TIN_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Activity_related',
        'name' => 'Trusted_Investor_Network_TIN_',
        'label' => E::ts('Trusted Investor Network (TIN)'),
        'data_type' => 'Boolean',
        'html_type' => 'Toggle',
        'default_value' => '0',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Related',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Investment_Related',
        'title' => E::ts('Investment-Related'),
        'extends' => 'Organization',
        'extends_entity_column_value' => ['Investor'],
        'collapse_display' => TRUE,
        'weight' => 4,
        'collapse_adv_display' => TRUE,
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Related_CustomField_Preferred_Stages',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Investment_Related',
        'name' => 'Preferred_Stages',
        'label' => E::ts('Preferred Stages'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'option_group_id.name' => 'eic_preferred_stages',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Related_CustomField_Relevant_Verticals',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Investment_Related',
        'name' => 'Relevant_Verticals',
        'label' => E::ts('Relevant Verticals'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'option_group_id.name' => 'eic_relevant_verticals',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Related_CustomField_Geographical_Focus',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Investment_Related',
        'name' => 'Geographical_Focus',
        'label' => E::ts('Geographical Focus'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'option_group_id.name' => 'eic_geographical_focus',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_ticket_size_range',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'eic_ticket_size_range',
        'title' => E::ts('Ticket Size Range'),
        'description' => E::ts('Ticket Size Range'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_ticket_size_range_OptionValue_0_500_000_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_ticket_size_range',
        'label' => E::ts('0 - <500,000€'),
        'value' => '0_500000',
        'name' => '0 - <500,000€',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_ticket_size_range_OptionValue_500_000_1_000_000_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_ticket_size_range',
        'label' => E::ts('500,000€ - <1,000,000€'),
        'value' => '500000_1000000',
        'name' => '500,000€ - <1,000,000€',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_ticket_size_range_OptionValue_1_000_000_2_500_000_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_ticket_size_range',
        'label' => E::ts('1,000,000€ - <2,500,000€'),
        'value' => '1000000_2500000',
        'name' => '1,000,000€ - <2,500,000€',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_ticket_size_range_OptionValue_2_500_000_5_000_000_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_ticket_size_range',
        'label' => E::ts('2,500,000€ - <5,000,000€'),
        'value' => '2500000_5000000',
        'name' => '2,500,000€ - <5,000,000€',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_ticket_size_range_OptionValue_5_000_000_10_000_000_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_ticket_size_range',
        'label' => E::ts('5,000,000€ - <10,000,000€'),
        'value' => '5000000_10000000',
        'name' => '5,000,000€ - <10,000,000€',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_ticket_size_range_OptionValue_10_000_000_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_ticket_size_range',
        'label' => E::ts('>10,000,000€'),
        'value' => '10000000_',
        'name' => '>10,000,000€',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Related_CustomField_Ticket_Size_Range_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Investment_Related',
        'name' => 'Ticket_Size_Range_',
        'label' => E::ts('Ticket Size Range (€)'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'option_group_id.name' => 'eic_ticket_size_range',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Related_CustomField_Current_Fund_Size_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Investment_Related',
        'name' => 'Current_Fund_Size_',
        'label' => E::ts('Current Fund Size (€)'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Related_CustomField_Estimated_Dry_Powder_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Investment_Related',
        'name' => 'Estimated_Dry_Powder_',
        'label' => E::ts('Estimated Dry Powder (€)'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_software_focus',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'eic_software_focus',
        'title' => E::ts('Software Focus'),
        'description' => E::ts('Software Focus'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_software_focus_OptionValue_Software_only',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_software_focus',
        'label' => E::ts('Software-only'),
        'value' => 'software_only',
        'name' => 'Software-only',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_software_focus_OptionValue_Hardware_only',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_software_focus',
        'label' => E::ts('Hardware-only'),
        'value' => 'hardware_only',
        'name' => 'Hardware-only',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_eic_software_focus_OptionValue_Both',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'eic_software_focus',
        'label' => E::ts('Both'),
        'value' => 'both',
        'name' => 'Both',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Related_CustomField_Software_Focus',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Investment_Related',
        'name' => 'Software_Focus',
        'label' => E::ts('Software Focus'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'option_group_id.name' => 'eic_software_focus',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Related_CustomField_Investment_Lead_Role',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Investment_Related',
        'name' => 'Investment_Lead_Role',
        'label' => E::ts('Investment Lead Role'),
        'data_type' => 'Boolean',
        'html_type' => 'Toggle',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Related_CustomField_Co_investments_with_public_sector',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Investment_Related',
        'name' => 'Co_investments_with_public_sector',
        'label' => E::ts('Co-investments with public sector'),
        'data_type' => 'Boolean',
        'html_type' => 'Toggle',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Investment_Related_CustomField_of_investments_made_in_vertical_in_the_last_2_years',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Investment_Related',
        'name' => '_of_investments_made_in_vertical_in_the_last_2_years',
        'label' => E::ts('# of investments made in vertical in the last 2 years'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_search_range' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Client_Roles',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Client_Roles',
        'title' => E::ts('Client Roles'),
        'extends' => 'Case',
        'extends_entity_column_value:name' => ['eic_engagement'],
        'collapse_display' => TRUE,
        'weight' => 5,
        'collapse_adv_display' => TRUE,
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'CustomGroup_Client_Roles_CustomField_Investor',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Client_Roles',
        'name' => 'Investor',
        'label' => E::ts('Investor'),
        'data_type' => 'EntityReference',
        'html_type' => 'Autocomplete-Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'filter' => 'contact_sub_type=Investor',
        'fk_entity' => 'Organization',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Client_Roles_CustomField_Beneficiary',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Client_Roles',
        'name' => 'Beneficiary',
        'label' => E::ts('Beneficiary'),
        'data_type' => 'EntityReference',
        'html_type' => 'Autocomplete-Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'filter' => 'contact_sub_type=EIC_Awardee',
        'fk_entity' => 'Organization',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Organisation_identifiers_CustomField_Company_Domain_Name',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Organisation_identifiers',
        'name' => 'Company_Domain_Name',
        'label' => E::ts('Company Domain Name'),
        'html_type' => 'Text',
        'text_length' => 512,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
