<?php
use CRM_EicConfig_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_EIC_Awardee_Additionnal_Information',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'EIC_Awardee_Additionnal_Information',
        'title' => E::ts('EIC Awardee Additionnal Information'),
        'extends' => 'Organization',
        'extends_entity_column_value' => ['EIC_Awardee'],
        'help_pre' => E::ts('<p>This information come from the EC corporate tools.</p>'),
        'weight' => 14,
        'collapse_adv_display' => TRUE,
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_EIC_Awardee_Additionnal_Information_Program_nh9i',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'EIC_Awardee_Additionnal_Information_Program_nh9i',
        'title' => E::ts('EIC Awardee Additionnal Information :: Program'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_EIC_Awardee_Additionnal_Information_Program_nh9i_OptionValue_EIC_Accelerator',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'EIC_Awardee_Additionnal_Information_Program_nh9i',
        'label' => E::ts('EIC Accelerator'),
        'value' => 'EIC Accelerator',
        'name' => 'EIC_Accelerator',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Awardee_Additionnal_Information_CustomField_Program',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Awardee_Additionnal_Information',
        'name' => 'Program',
        'label' => E::ts('Program'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'option_group_id.name' => 'EIC_Awardee_Additionnal_Information_Program_nh9i',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Awardee_Additionnal_Information_CustomField_Research_organisation',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Awardee_Additionnal_Information',
        'name' => 'Research_organisation',
        'label' => E::ts('Research organisation'),
        'data_type' => 'Boolean',
        'html_type' => 'Toggle',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Awardee_Additionnal_Information_CustomField_Large_research_infrastructure',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Awardee_Additionnal_Information',
        'name' => 'Large_research_infrastructure',
        'label' => E::ts('Large research infrastructure'),
        'data_type' => 'Boolean',
        'html_type' => 'Toggle',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Awardee_Additionnal_Information_CustomField_Non_profit_organisation',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Awardee_Additionnal_Information',
        'name' => 'Non_profit_organisation',
        'label' => E::ts('Non-profit organisation'),
        'data_type' => 'Boolean',
        'html_type' => 'Toggle',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Awardee_Additionnal_Information_CustomField_Public_body',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Awardee_Additionnal_Information',
        'name' => 'Public_body',
        'label' => E::ts('Public body'),
        'data_type' => 'Boolean',
        'html_type' => 'Toggle',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Awardee_Additionnal_Information_CustomField_International_organisation',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Awardee_Additionnal_Information',
        'name' => 'International_organisation',
        'label' => E::ts('International organisation'),
        'data_type' => 'Boolean',
        'html_type' => 'Toggle',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Awardee_Additionnal_Information_CustomField_European_interest',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Awardee_Additionnal_Information',
        'name' => 'European_interest',
        'label' => E::ts('European interest'),
        'data_type' => 'Boolean',
        'html_type' => 'Toggle',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_EIC_Awardee_Additionnal_Information_Legal_status',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'EIC_Awardee_Additionnal_Information_Legal_status',
        'title' => E::ts('EIC Awardee Additionnal Information :: Legal status'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_EIC_Awardee_Additionnal_Information_Legal_status_OptionValue_LEGAL_PERSON',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'EIC_Awardee_Additionnal_Information_Legal_status',
        'label' => E::ts('LEGAL_PERSON'),
        'value' => 'LEGAL_PERSON',
        'name' => 'LEGAL_PERSON',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Awardee_Additionnal_Information_CustomField_Legal_status',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Awardee_Additionnal_Information',
        'name' => 'Legal_status',
        'label' => E::ts('Legal status'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'option_group_id.name' => 'EIC_Awardee_Additionnal_Information_Legal_status',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_EIC_Awardee_Additionnal_Information_SME_vs_mid_cap_status',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'EIC_Awardee_Additionnal_Information_SME_vs_mid_cap_status',
        'title' => E::ts('EIC Awardee Additionnal Information :: SME vs mid-cap status'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_EIC_Awardee_Additionnal_Information_SME_vs_mid_cap_status_OptionValue_Not_an_SME',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'EIC_Awardee_Additionnal_Information_SME_vs_mid_cap_status',
        'label' => E::ts('Not an SME'),
        'value' => 'Not an SME',
        'name' => 'Not_an_SME',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_EIC_Awardee_Additionnal_Information_SME_vs_mid_cap_status_OptionValue_N_A',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'EIC_Awardee_Additionnal_Information_SME_vs_mid_cap_status',
        'label' => E::ts('N/A'),
        'value' => 'N/A',
        'name' => 'N_A',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_EIC_Awardee_Additionnal_Information_SME_vs_mid_cap_status_OptionValue_SME',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'EIC_Awardee_Additionnal_Information_SME_vs_mid_cap_status',
        'label' => E::ts('SME'),
        'value' => 'SME',
        'name' => 'SME',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_EIC_Awardee_Additionnal_Information_SME_vs_mid_cap_status_OptionValue_Mid_cap',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'EIC_Awardee_Additionnal_Information_SME_vs_mid_cap_status',
        'label' => E::ts('Mid-cap'),
        'value' => 'Mid-cap',
        'name' => 'Mid_cap',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_EIC_Awardee_Additionnal_Information_SME_vs_mid_cap_status_OptionValue_SME',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'EIC_Awardee_Additionnal_Information_SME_vs_mid_cap_status',
        'label' => E::ts('SME'),
        'value' => '3',
        'name' => 'SME',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Awardee_Additionnal_Information_CustomField_SME_vs_mid_cap_status',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Awardee_Additionnal_Information',
        'name' => 'SME_vs_mid_cap_status',
        'label' => E::ts('SME vs mid-cap status'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'option_group_id.name' => 'EIC_Awardee_Additionnal_Information_SME_vs_mid_cap_status',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_EIC_Awardee_Additionnal_Information_SME_status_type',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'EIC_Awardee_Additionnal_Information_SME_status_type',
        'title' => E::ts('EIC Awardee Additionnal Information :: SME status type'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_EIC_Awardee_Additionnal_Information_SME_status_type_OptionValue_Self_assessment',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'EIC_Awardee_Additionnal_Information_SME_status_type',
        'label' => E::ts('Self-assessment'),
        'value' => 'Self-assessment',
        'name' => 'Self_assessment',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_EIC_Awardee_Additionnal_Information_SME_status_type_OptionValue_N_A',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'EIC_Awardee_Additionnal_Information_SME_status_type',
        'label' => E::ts('N/A'),
        'value' => 'N/A',
        'name' => 'N_A',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_EIC_Awardee_Additionnal_Information_SME_status_type_OptionValue_Validation_services',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'EIC_Awardee_Additionnal_Information_SME_status_type',
        'label' => E::ts('Validation services'),
        'value' => 'Validation services',
        'name' => 'Validation_services',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Awardee_Additionnal_Information_CustomField_SME_status_type',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Awardee_Additionnal_Information',
        'name' => 'SME_status_type',
        'label' => E::ts('SME status type'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'option_group_id.name' => 'EIC_Awardee_Additionnal_Information_SME_status_type',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Awardee_Additionnal_Information_CustomField_higher_or_secondary_education_establishment',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Awardee_Additionnal_Information',
        'name' => 'higher_or_secondary_education_establishment',
        'label' => E::ts('Higher or secondary education establishment'),
        'data_type' => 'Boolean',
        'html_type' => 'Toggle',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Awardee_Additionnal_Information_CustomField_Legal_personality',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Awardee_Additionnal_Information',
        'name' => 'Legal_personality',
        'label' => E::ts('Legal personality'),
        'data_type' => 'Boolean',
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
