<?php
use CRM_EicEuSurveyFormProcessor_ExtensionUtil as E;

// EIC Fundraising Assessment - company-level custom group.
//
// Holds the answers of the EIC VM Fundraising Assessment EU-Survey that describe
// the company. Stored on the Organisation (sub-types EIC_Awardee / EIC_Organisation)
// rather than on the VentureMatch case, because these are reusable company
// attributes. Populated by the FormProcessor `eic_vm_fundraising_assessment_eu_survey_import`.
//
// All entities use update=always for cross-environment determinism.

return [
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'EIC_Fundraising_Assessment',
        'title' => E::ts('EIC Fundraising Assessment'),
        'extends' => 'Organization',
        'extends_entity_column_value:name' => ['EIC_Awardee', 'EIC_Organisation'],
        'weight' => 14,
        'collapse_adv_display' => TRUE,
        'help_pre' => E::ts('<p>Company fundraising data received through the EIC VM Fundraising Assessment EU-Survey.</p>'),
        'table_name' => 'civicrm_value_srm_eic_fundraising_assess',
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment_CustomField_Primary_Sector_Cluster',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Fundraising_Assessment',
        'name' => 'Primary_Sector_Cluster',
        'label' => E::ts('Primary Sector / Industry Cluster'),
        'html_type' => 'Select',
        'option_group_id.name' => 'eic_vm_sector_cluster',
        'is_searchable' => TRUE,
        'help_post' => E::ts('From the EIC VM Fundraising Assessment EU-Survey. Distinct from the EU-Survey onboarding Sector.'),
        'column_name' => 'primary_sector_cluster',
      ],
      'match' => ['name', 'custom_group_id'],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment_CustomField_Current_Fundraising_Round',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Fundraising_Assessment',
        'name' => 'Current_Fundraising_Round',
        'label' => E::ts('Current Fundraising Round'),
        'html_type' => 'Select',
        'option_group_id.name' => 'eic_vm_fundraising_round',
        'is_searchable' => TRUE,
        'help_post' => E::ts('From the EIC VM Fundraising Assessment EU-Survey.'),
        'column_name' => 'current_fundraising_round',
      ],
      'match' => ['name', 'custom_group_id'],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment_CustomField_Amount_Currently_Raising',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Fundraising_Assessment',
        'name' => 'Amount_Currently_Raising',
        'label' => E::ts('Amount Currently Raising (EUR)'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'text_length' => 255,
        'help_post' => E::ts('From the EIC VM Fundraising Assessment EU-Survey.'),
        'column_name' => 'amount_currently_raising',
      ],
      'match' => ['name', 'custom_group_id'],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment_CustomField_Current_Runway_Months',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Fundraising_Assessment',
        'name' => 'Current_Runway_Months',
        'label' => E::ts('Current Runway (months)'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'text_length' => 255,
        'help_post' => E::ts('From the EIC VM Fundraising Assessment EU-Survey.'),
        'column_name' => 'current_runway_months',
      ],
      'match' => ['name', 'custom_group_id'],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment_CustomField_Raised_Capital_Before',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Fundraising_Assessment',
        'name' => 'Raised_Capital_Before',
        'label' => E::ts('Have you raised capital before?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'help_post' => E::ts('From the EIC VM Fundraising Assessment EU-Survey.'),
        'column_name' => 'raised_capital_before',
      ],
      'match' => ['name', 'custom_group_id'],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment_CustomField_Current_Key_Investors',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Fundraising_Assessment',
        'name' => 'Current_Key_Investors',
        'label' => E::ts('List Current Key Investors'),
        'html_type' => 'TextArea',
        'note_columns' => 60,
        'note_rows' => 4,
        'help_post' => E::ts('From the EIC VM Fundraising Assessment EU-Survey. VCs, Angels, Corporate VCs, etc. - separated by ";".'),
        'column_name' => 'current_key_investors',
      ],
      'match' => ['name', 'custom_group_id'],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment_CustomField_Total_Amount_Raised',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Fundraising_Assessment',
        'name' => 'Total_Amount_Raised',
        'label' => E::ts('Total Amount Raised to Date (EUR)'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'text_length' => 255,
        'help_post' => E::ts('From the EIC VM Fundraising Assessment EU-Survey.'),
        'column_name' => 'total_amount_raised',
      ],
      'match' => ['name', 'custom_group_id'],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment_CustomField_Target_Close_Date',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Fundraising_Assessment',
        'name' => 'Target_Close_Date',
        'label' => E::ts('Target Close Date for Current Round'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'date_format' => 'dd/mm/yy',
        'help_post' => E::ts('From the EIC VM Fundraising Assessment EU-Survey.'),
        'column_name' => 'target_close_date',
      ],
      'match' => ['name', 'custom_group_id'],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment_CustomField_Intended_Use_Of_Funds',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Fundraising_Assessment',
        'name' => 'Intended_Use_Of_Funds',
        'label' => E::ts('Intended Use of Funds (current round)'),
        'html_type' => 'TextArea',
        'note_columns' => 60,
        'note_rows' => 4,
        'help_post' => E::ts('From the EIC VM Fundraising Assessment EU-Survey.'),
        'column_name' => 'intended_use_of_funds',
      ],
      'match' => ['name', 'custom_group_id'],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment_CustomField_Link_Pitchdeck',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Fundraising_Assessment',
        'name' => 'Link_Pitchdeck',
        'label' => E::ts('Link to Pitchdeck'),
        'data_type' => 'Link',
        'html_type' => 'Link',
        'text_length' => 512,
        'help_post' => E::ts('From the EIC VM Fundraising Assessment EU-Survey.'),
        'column_name' => 'link_pitchdeck',
      ],
      'match' => ['name', 'custom_group_id'],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment_CustomField_Link_Financial_Model',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Fundraising_Assessment',
        'name' => 'Link_Financial_Model',
        'label' => E::ts('Existing Metrics / Financial Model Link'),
        'data_type' => 'Link',
        'html_type' => 'Link',
        'text_length' => 512,
        'help_post' => E::ts('From the EIC VM Fundraising Assessment EU-Survey.'),
        'column_name' => 'link_financial_model',
      ],
      'match' => ['name', 'custom_group_id'],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment_CustomField_Link_Data_Room',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Fundraising_Assessment',
        'name' => 'Link_Data_Room',
        'label' => E::ts('Existing Metrics / Data Room Link'),
        'data_type' => 'Link',
        'html_type' => 'Link',
        'text_length' => 512,
        'help_post' => E::ts('From the EIC VM Fundraising Assessment EU-Survey.'),
        'column_name' => 'link_data_room',
      ],
      'match' => ['name', 'custom_group_id'],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment_CustomField_Priorities',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Fundraising_Assessment',
        'name' => 'Priorities',
        'label' => E::ts('Priorities'),
        'html_type' => 'Select',
        'option_group_id.name' => 'eic_vm_priorities',
        'serialize' => 1,
        'is_searchable' => TRUE,
        'help_post' => E::ts('From the EIC VM Fundraising Assessment EU-Survey. Respondent selects one or two.'),
        'column_name' => 'priorities',
      ],
      'match' => ['name', 'custom_group_id'],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment_CustomField_Dealroom_Profile',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Fundraising_Assessment',
        'name' => 'Dealroom_Profile',
        'label' => E::ts('Dealroom Profile Link / Dealroom Company ID'),
        'html_type' => 'Text',
        'text_length' => 512,
        'help_post' => E::ts('From the EIC VM Fundraising Assessment EU-Survey.'),
        'column_name' => 'dealroom_profile',
      ],
      'match' => ['name', 'custom_group_id'],
    ],
  ],
  [
    'name' => 'CustomGroup_EIC_Fundraising_Assessment_CustomField_Country_Of_Incorporation',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'EIC_Fundraising_Assessment',
        'name' => 'Country_Of_Incorporation',
        'label' => E::ts('Country of Incorporation / Primary Operation'),
        'html_type' => 'Text',
        'text_length' => 255,
        'help_post' => E::ts('From the EIC VM Fundraising Assessment EU-Survey.'),
        'column_name' => 'country_of_incorporation',
      ],
      'match' => ['name', 'custom_group_id'],
    ],
  ],
];
