<?php
use CRM_EicEuSurveyFormProcessor_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_EIC_Service_Request_All',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'EIC_Service_Request_All',
        'label' => E::ts('EIC Service Request All'),
        'api_entity' => 'Case',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'subject',
            'Case_CaseContact_Contact_01.sort_name',
            'status_id:label',
            'start_date',
            'end_date',
            'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id.display_name',
            'Client_Roles.EIC_Awardee',
          ],
          'orderBy' => [],
          'where' => [
            [
              'case_type_id:name',
              'CONTAINS ONE OF',
              [
                'eic_sr_community',
                'eic_sr_women_leadership',
                'eic_sr_venturematch',
                'eic_sr_international_trade_fairs',
                'eic_sr_innovation_procurement',
                'eic_sr_innonext',
                'eic_sr_global_business_expansion',
                'eic_sr_ecosystem_partnership',
                'eic_sr_corporate_partnership',
                'eic_sr_coaching',
              ],
            ],
          ],
          'groupBy' => [],
          'join' => [
            [
              'Contact AS Case_CaseContact_Contact_01',
              'LEFT',
              'CaseContact',
              [
                'id',
                '=',
                'Case_CaseContact_Contact_01.case_id',
              ],
            ],
            [
              'Case AS Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01',
              'LEFT',
              'RelationshipCache',
              [
                'Case_CaseContact_Contact_01.id',
                '=',
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.far_contact_id',
              ],
              [
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id',
                '=',
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.case_manager_id',
              ],
              [
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.id',
                '=',
                'id',
              ],
              [
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.is_active',
                '=',
                TRUE,
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_EIC_Service_Request_All_SearchDisplay_EIC_Service_Requests',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'EIC_Service_Requests',
        'label' => E::ts('My EIC Service Requests'),
        'saved_search_id.name' => 'EIC_Service_Request_All',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [
            ['start_date', 'ASC'],
          ],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'actions' => ['case.addRole', 'tag', 'update'],
          'classes' => [
            'table',
            'table-striped',
            'crm-sticky-header',
          ],
          'columnMode' => 'custom',
          'columns' => [
            [
              'type' => 'field',
              'key' => 'subject',
              'label' => E::ts('Programme'),
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Case',
                'action' => 'view',
                'join' => '',
                'target' => '_blank',
                'task' => '',
              ],
              'title' => E::ts('View Case'),
            ],
            [
              'type' => 'field',
              'key' => 'Case_CaseContact_Contact_01.sort_name',
              'label' => E::ts('Organisation'),
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'Case_CaseContact_Contact_01',
                'target' => '_blank',
                'task' => '',
              ],
              'title' => E::ts('View Case Clients'),
            ],
            [
              'type' => 'field',
              'key' => 'status_id:label',
              'label' => E::ts('Case Status'),
              'sortable' => TRUE,
              'colors' => [
                [
                  'field' => 'status_id:color',
                ],
              ],
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'start_date',
              'label' => E::ts('Start Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'end_date',
              'label' => E::ts('End Date'),
              'sortable' => TRUE,
              'editable' => TRUE,
              'show_linebreaks' => FALSE,
              'format' => 'dateformatshortdate',
            ],
            [
              'type' => 'field',
              'key' => 'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id.display_name',
              'label' => E::ts('Case Manager'),
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id',
                'target' => 'crm-popup',
                'task' => '',
              ],
              'title' => E::ts('View case Manager'),
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'entity' => 'Case',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-user-plus',
                  'text' => E::ts('Case - Assign Role'),
                  'style' => 'default',
                  'path' => '',
                  'task' => 'case.addRole',
                  'conditions' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'headerCount' => TRUE,
          'actions_display_mode' => 'menu',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_EIC_Service_Request_All_SearchDisplay_EIC_Service_Requests_0xvh',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'EIC_Service_Requests_0xvh',
        'label' => E::ts('EIC Service Requests'),
        'saved_search_id.name' => 'EIC_Service_Request_All',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [
            ['start_date', 'ASC'],
          ],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'actions' => ['case.addRole', 'tag', 'update'],
          'classes' => [
            'table',
            'table-striped',
            'crm-sticky-header',
          ],
          'columnMode' => 'custom',
          'columns' => [
            [
              'type' => 'field',
              'key' => 'subject',
              'label' => E::ts('Programme'),
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Case',
                'action' => 'view',
                'join' => '',
                'target' => '_blank',
                'task' => '',
              ],
              'title' => E::ts('View Case'),
            ],
            [
              'type' => 'field',
              'key' => 'Case_CaseContact_Contact_01.sort_name',
              'label' => E::ts('Organisation'),
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'Case_CaseContact_Contact_01',
                'target' => '_blank',
                'task' => '',
              ],
              'title' => E::ts('View Case Clients'),
            ],
            [
              'type' => 'field',
              'key' => 'status_id:label',
              'label' => E::ts('Case Status'),
              'sortable' => TRUE,
              'colors' => [
                [
                  'field' => 'status_id:color',
                ],
              ],
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'start_date',
              'label' => E::ts('Start Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'end_date',
              'label' => E::ts('End Date'),
              'sortable' => TRUE,
              'editable' => TRUE,
              'show_linebreaks' => FALSE,
              'format' => 'dateformatshortdate',
            ],
            [
              'type' => 'field',
              'key' => 'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id.display_name',
              'label' => E::ts('Case Manager'),
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id',
                'target' => 'crm-popup',
                'task' => '',
              ],
              'title' => E::ts('View case Manager'),
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'entity' => 'Case',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-user-plus',
                  'text' => E::ts('Case - Assign Role'),
                  'style' => 'default',
                  'path' => '',
                  'task' => 'case.addRole',
                  'conditions' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'headerCount' => TRUE,
          'actions_display_mode' => 'menu',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_EIC_Service_Request_All_SearchDisplay_EIC_Service_Requests_organisation',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'EIC_Service_Requests_organisation',
        'label' => E::ts('EIC Service Requests organisation'),
        'saved_search_id.name' => 'EIC_Service_Request_All',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [
            ['start_date', 'ASC'],
          ],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'actions' => ['case.addRole', 'tag', 'update'],
          'classes' => [
            'table',
            'table-striped',
            'crm-sticky-header',
          ],
          'columnMode' => 'custom',
          'columns' => [
            [
              'type' => 'field',
              'key' => 'subject',
              'label' => E::ts('Programme'),
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Case',
                'action' => 'view',
                'join' => '',
                'target' => '_blank',
                'task' => '',
              ],
              'title' => E::ts('View Case'),
            ],
            [
              'type' => 'field',
              'key' => 'status_id:label',
              'label' => E::ts('Case Status'),
              'sortable' => TRUE,
              'colors' => [
                [
                  'field' => 'status_id:color',
                ],
              ],
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'start_date',
              'label' => E::ts('Start Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'end_date',
              'label' => E::ts('End Date'),
              'sortable' => TRUE,
              'editable' => TRUE,
              'show_linebreaks' => FALSE,
              'format' => 'dateformatshortdate',
            ],
            [
              'type' => 'field',
              'key' => 'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id.display_name',
              'label' => E::ts('Case Manager'),
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id',
                'target' => 'crm-popup',
                'task' => '',
              ],
              'title' => E::ts('View case Manager'),
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'entity' => 'Case',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-user-plus',
                  'text' => E::ts('Case - Assign Role'),
                  'style' => 'default',
                  'path' => '',
                  'task' => 'case.addRole',
                  'conditions' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'headerCount' => TRUE,
          'actions_display_mode' => 'menu',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
